on: [push, pull_request]
jobs:
  hello-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Commit Message On Push
        uses: ./.github/actions/commitNotes
        id: hello