on: push
jobs:
  hello-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/commitNotes
        id: hello
        with:
          who-to-greet: "World1!!"
